services:
  backend-nodejs:
    build:
      context: ./backend-nodejs
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DATABASE_TYPE=sqlite
      - SQLITE_DATABASE_URL=sqlite:///instance/insurance.db
    volumes:
      - backend_data:/app/instance
    networks:
      - insurance-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5000/api/health" ]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend-react:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    depends_on:
      - backend-nodejs
    networks:
      - insurance-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000" ]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  backend_data:
    driver: local

networks:
  insurance-network:
    driver: bridge
